# Generated by Django 4.2.20 on 2025-03-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Customer Segment', 'verbose_name_plural': 'Customer Segments'},
        ),
        migrations.AddField(
            model_name='billline',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billline',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.segment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment_info',
            field=models.CharField(max_length=255),
        ),
    ]
