# Generated by Django 4.2.20 on 2025-03-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_segment_options_billline_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='billline',
            name='total_price',
        ),
    ]
